# Generated by Django 3.1.7 on 2021-03-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.CharField(default='mehh', max_length=200),
            preserve_default=False,
        ),
    ]
